use travel_agency_2025;
CREATE TABLE numbers (
  n INT PRIMARY KEY
);

INSERT INTO numbers (n)
SELECT a.n + b.n * 10 + c.n * 100 + d.n * 1000
FROM
 (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
 (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
 (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
 (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d;

INSERT INTO trip_history (
  tr_h_departure,
  tr_h_return,
  tr_h_dst_count,
  tr_h_participants,
  tr_h_income
)
SELECT
  DATE_ADD('2024-01-01 08:00:00', INTERVAL (n1.n * 12) HOUR),
  DATE_ADD(
    DATE_ADD('2024-01-01 08:00:00', INTERVAL (n1.n * 12) HOUR),
    INTERVAL (2 + (n1.n % 9)) DAY
  ),
  CASE
    WHEN n1.n % 100 < 50 THEN 1
    WHEN n1.n % 100 < 75 THEN 2
    WHEN n1.n % 100 < 90 THEN 3
    WHEN n1.n % 100 < 97 THEN 4
    WHEN n1.n % 99 < 99 THEN 6
    ELSE 8
  END,
  10 + (n1.n % 30),
  (10 + (n1.n % 30)) * (200 + (n1.n % 400))
FROM numbers n1
JOIN numbers n2
LIMIT 500000;
